### ISSUE TITLE
Exit directly after copying

### ISSUE THREAD

**Issue by TaceyWong** [golang-design/clipboard#15]
if :
```go
clipboard.Write(clipboard.FmtText, []byte("hello world"))
exit()
```
or
```go
clipboard.Write(clipboard.FmtImage, content)
exit()
```
there will be nothing in clipboard
else:
```
<-clipboard.Write(clipboard.FmtText, []byte(imagePath))
```
clipboard is ok,but program is blocked untill something new  is copied into clipboad .

---

ubuntu20.04

**Comment by changkun** [comment]
This is an expected behavior on Linux systems.

**Comment by TaceyWong** [comment]
thx for your  reply . Maybe I need adjust the flow of my program.

after copying,add a time sleep,it will be ok.

Is there a  sync-way  to execute copy-work,or, an async-way but can be notified in `select` style after copy-work completed.

**Comment by changkun** [comment]
This is how X11 clipboard systems should work. Clipboard writers must stay live in order to serve the copy requests from others until the next writer writes new content.

The application should either stay to not exit or run in the background. See [gclip](https://github.com/golang-design/clipboard/tree/main/cmd/gclip) as a clipboard example.

Close as this is as being said an expected behavior in X11 systems.
